### ISSUE TITLE
Feature questions

### ISSUE THREAD

**Issue by shierru** [openmultiplayer/open.mp-sdk#33]
1. For some reason there is no function to kill a player. Although, as an option, you can just set his HP 0.0. If the task will be to have someone kill the player, and not himself, then what to do? Involuntarily call **onPlayerDeath**, and independently specify the identifier of the killer?

2. I would like to have a function analogous to Pawn function **SetSpawInfo**, so you can specify the spawn coordinates, which will stand by default. It would be very cool if through the function **connectBot** could join a bot, without a prescribed script (route), and it would be possible to manage it, as a normal player. 

This is all I came across using the open.mp SDK. Perhaps some of my questions are useless or implemented and much easier.

That's what issue's are for. 

(^_^)

**Comment by Hual** [comment]
There's IPlayerClassData::setSpawnInfo
