### ISSUE TITLE
About nonstd, robin_hood and glm

### ISSUE THREAD

**Issue by punkochel** [openmultiplayer/open.mp-sdk#36]
Why not put third-party libraries like nonstd (span, string_view), robin_hood and glm inside the sdk? Or can at least make a mention that they must be present in the system?
This is misleading when generating a compilation database.

P.S.
Sorry for my english... Google translate :)

**Comment by shierru** [comment]
I disagree with the first one. 
I agree with the second, it would be nice if it was specified in the additional dependencies.

P.S.
I don't use Google translator, I use Deepl Translate (^_^)

**Comment by AmyrAhmady** [comment]
you are required to use cmake, and if you do, it'll tell you about them.
